language: bash

addons:
  apt:
    packages:
    - shellcheck

script:
  - ./travis-build.sh

notifications:
  slack:
    secure: cdJk4p6UsiR+4KEAIZISX+pKQG23jlCxdK9W3jNST3bhsmbWLCEALM8tIGTl5qqVM81FfNhZ9k7ylglrEckUk7w29pVvM3pQcgn5Rtl0k4/o5eGOukZN+6qal2US8yAXpZkuc1Xx89XLtPQ9bNTsHVnFTatYm6UxzNkHGfpLdgI=
