name: Testing urda.bash


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  make-test:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout ⬇️
        uses: actions/checkout@v5

      - name: Report `shellcheck` Version 🔍
        run: shellcheck --version

      - name: urda.bash Testing 🧪
        run: make test
